"""
Django settings for misperris project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

from django.urls import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static/js', 'serviceworker.js')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=-41umw=tjde&h7n295+%oowtee5*1&-=e7$=do@9w0t#w2kjq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.rescatado',
    'apps.adopcion',
    'apps.usuario',
    'materializecssform',
    # para agregar django rest 
    'rest_framework',
    # para lograr hacer una app progresiva
    'pwa',
    # para conectar con Redes sociales
    'social_django',
    # para agregar protocolo https
    'sslserver',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',


    # Para django social, conectar con Redes sociales
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'misperris.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Para django social, para conectar con Redes sociales
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
           
            ],
        },
    },
]

WSGI_APPLICATION = 'misperris.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    # para loguearse con github
    'social_core.backends.github.GithubOAuth2',
    # para loguearse con Twitter
    'social_core.backends.twitter.TwitterOAuth',
    # para loguearse con Facebook
    'social_core.backends.facebook.FacebookOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)
# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

LOGIN_REDIRECT_URL = reverse_lazy('rescatado_listar')

LOGOUT_REDIRECT_URL = reverse_lazy('index')

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

###########################################################################################
# datos privados de app facebook                                                          
SOCIAL_AUTH_FACEBOOK_KEY = '294444797838200'
SOCIAL_AUTH_FACEBOOK_SECRET = '6153e7107b8603b46a963720a1ace229'

# datos privados para iniciar con twitter NO FUNCIONA
SOCIAL_AUTH_TWITTER_KEY = 'iRGYqmIfscuzE3SKb6fZyqZMM'
SOCIAL_AUTH_TWITTER_SECRET = 'pg3jcbi9Le20ib5i0V3Xw8s9MAKbiNrj4PuVnCEc7rhvNhzE4Y'

# datos privados para iniciar con github
SOCIAL_AUTH_GITHUB_KEY = '886b93715759bc639333'
SOCIAL_AUTH_GITHUB_SECRET = 'affcc6de533955080c3e8576f3e521a39b52ee99'

###########################################################################################



EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'librerialmg@gmail.com'
EMAIL_HOST_PASSWORD = 'lapizlopez'

EMAIL_PORT = 587
ACCOUNT_EMAIL_VERIFICATION = 'none'

