# Generated by Django 2.1.2 on 2018-10-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescatado', '0002_auto_20181020_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescatado',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rescatado',
            name='fotografia',
            field=models.CharField(default='.jpg', max_length=200),
        ),
    ]
